services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant  # Ensure backend waits for Qdrant
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      OLLAMA_HOST: host.docker.internal
      OLLAMA_PORT: 11434

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"  # nginx port mapping 

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"     # REST API
      - "6334:6334"     # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
